version: "3.8"

services:
  znuny:
    image: ghcr.io/nyanmark/znuny:latest
    restart: always
    container_name: znuny
    ports:
      - 80:80
    volumes:
      - ./config.pm:/opt/otrs/Kernel/Config.pm
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: otrs
      POSTGRES_PASSWORD: mjeffomybyov7xffcba6
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
